name: Secure DevSecOps Pipeline

on:
  push:
    branches:
      - master
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24 : true

jobs:
  build_and_package:
    name: BUILD-JOB
    runs-on: ubuntu-slim
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build the code
      uses: npm ci

    - name: Test
      uses: echo "code is tested!"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: production-build       # The downloadable name of the zip file
        path: package-*/                  # The directory or file path you want to upload
        retention-days: 7            # Optional: How long to keep it (default 90)
        compression-level: 6        
