name: CI-WORKFLOW 
on:
 push:
 
jobs: 
  build-test: 
    name: BUILD_JOB
   # if: github.ref == 'ref/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-slim

    permissions:
     actions: read
     contents: read
     security-events: write
     
    steps: 
      - name: checkout 
        uses: actions/checkout@v4
 
      - name: Cache Dependencies 
        uses: actions/cache@v5 
        with: 
          path: ~/.npm 
          key:  ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} 
 
      - name: build 
        run: npm install 
 
      - name: test 
        run: npm test 
 
      - name: Artifact upload 
        uses: actions/upload-artifact@v7 
        with: 
          name: artifact-1 
          path: | 
             package* 

      - name: deploy
        run: ech0 "my code is deployed"
        
      - name: rollback
        if: failure()
        run: echo "rollback is done"
        

 
 
      - name: deploy 
        run: echo "my code is deployed"
